<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classements</h1>
    </div>
</div>

<div class="row mt-20">
    <div class="col-md-12 text-center">

        <form <?= $this->url('classement') ?> method="GET" id="classement">

            <div class="form-group">
                <label for="selectEvent">Sélectionner la catégorie</label>
                <select class="form-control" id="sex" name="sex" form="classement">
                    <option <?php if ($this->sex === "all") : ?>
                            selected="selected"
                            <?php endif ?>
                            value=all>Mixte</option>
                    <option <?php if ($this->sex === "male") : ?>
                        selected="selected"
                            <?php endif ?>
                            value=male>Homme</option>
                    <option <?php if ($this->sex === "female") : ?>
                            selected="selected"
                            <?php endif ?>
                            value=female>Femme</option>
                </select>
            </div>


            <div class="form-group">
                <label for="selectEvent">Sélectionner l'événement</label>
                <select class="form-control" id="selectEvent" name="event" form="classement">
                    <?php if ($this->events) { ?>
                        <?php
                        /** @var \Application\Entity\User $participant */
                        foreach ($this->events as $event) { ?>
                            <option <?php if ($this->event === $event->getId()) : ?>
                                    selected="selected"
                                    <?php endif ?>
                                    value=<?=$event->getId()?>><?=$event->getName()?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <div class="table-responsive mt-20">
            <table class="table">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Nom</td>
                    <td>Prénom</td>
                    <td>Temps</td>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->participants) { ?>
                    <?php
                    /** @var \Application\Entity\User $participant */
                    foreach ($this->participants as $participant) { ?>
                        <tr>
                            <td><?=$participant->getDossardNumber()?></td>
                            <td><?=$participant->getFirstname()?></td>
                            <td><?=$participant->getLastname()?></td>
                            <td><?=$participant->getMeasuredTime()?></td>
                        </tr>
                    <?php } ?>
                <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
