<div class="row">
    <div class="col-md-12 text-center">
        <h1>Classements</h1>
    </div>
</div>

<div class="row mt-20">
    <div class="col-md-12 text-center">

        <div class="table-responsive mt-20">
            <table class="table">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Nom</td>
                    <td>Prénom</td>
                    <td>Temps</td>
                </tr>
                </thead>
                <tbody>
                <?php if($this->participants){ ?>
                    <?php
                    /** @var \Application\Entity\User $participant */
                    foreach($this->participants as $participant){ ?>
                        <tr>
                            <td><?=$participant->getId()?></td>
                            <td><?=$participant->getFirstname()?></td>
                            <td><?=$participant->getLastname()?></td>
                            <td><?=$participant->getMeasuredTime()?></td>
                        </tr>
                    <?php } ?>
                <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
